name: DB Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make scripts executable
        run: chmod +x *.sh

      - name: Setup Database
        run: ./setup_db.sh

      - name: "Test: count users"
        run: ./test_count.sh

      - name: "Test: check user 1 name"
        run: ./test_value.sh
